//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pruebasEntities : DbContext
    {
        public pruebasEntities()
            : base("name=pruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<vehículo> vehículo { get; set; }
        public virtual DbSet<vendedor> vendedor { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    
        public virtual ObjectResult<vehiculosVendedor_Result> vehiculosVendedor(Nullable<long> cedula)
        {
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vehiculosVendedor_Result>("vehiculosVendedor", cedulaParameter);
        }
    }
}
