//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public long cedula { get; set; }
        public string Nombre_vendedor { get; set; }
        public string Apellido_vendedor { get; set; }
        public string Matricula { get; set; }
        public string Marca { get; set; }
        public string Color_Auto { get; set; }
        public double Valor_Unitario { get; set; }
        public double Valor_Total { get; set; }
        public Nullable<System.DateTime> Fecha_venta { get; set; }
        public int ID { get; set; }
    }
}
